"""empty message

Revision ID: 807d7c6c3216
Revises: 
Create Date: 2022-12-03 11:43:39.972647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '807d7c6c3216'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('mainTitleVideo', sa.String(length=500), nullable=True),
    sa.Column('thirdSectionLeftConceptOneImg', sa.String(length=500), nullable=True),
    sa.Column('thirdSectionRightConceptTwoImg', sa.String(length=500), nullable=True),
    sa.Column('thirdSectionLeftConceptThreeImg', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('text_firstsection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mainTitle', sa.String(length=200), nullable=True),
    sa.Column('mainDescription', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('text_fourthsection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fourthSection_TestimonialsMainTitle', sa.String(length=200), nullable=True),
    sa.Column('fourthSection_TestimonialsDescription', sa.String(length=200), nullable=True),
    sa.Column('fourthSection_CardOneText', sa.String(length=200), nullable=True),
    sa.Column('fourthSection_CardOne_Person', sa.String(length=200), nullable=True),
    sa.Column('fourthSection_CardTwoText', sa.String(length=200), nullable=True),
    sa.Column('fourthSection_CardTwo_Person', sa.String(length=200), nullable=True),
    sa.Column('fourthSection_CardThreeText', sa.String(length=200), nullable=True),
    sa.Column('fourthSection_CardThree_Person', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('text_secondsection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('secondSection_MainTitle', sa.String(length=200), nullable=True),
    sa.Column('secondSection_Description', sa.String(length=200), nullable=True),
    sa.Column('secondSection_ConceptOne', sa.String(length=200), nullable=True),
    sa.Column('secondSection_ConceptTwo', sa.String(length=200), nullable=True),
    sa.Column('secondSection_ConceptThree', sa.String(length=200), nullable=True),
    sa.Column('secondSection_ConceptFour', sa.String(length=200), nullable=True),
    sa.Column('secondSection_ConceptFive', sa.String(length=200), nullable=True),
    sa.Column('secondSection_ConceptSix', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('text_thirdsection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('thirdSection_MainTitle', sa.String(length=200), nullable=True),
    sa.Column('thirdSection_Description', sa.String(length=200), nullable=True),
    sa.Column('thirdSection_LeftConceptOne_BlueHighlightText', sa.String(length=200), nullable=True),
    sa.Column('thirdSection_LeftConceptOne_Title', sa.String(length=200), nullable=True),
    sa.Column('thirdSection_LeftConceptOne_Description', sa.String(length=200), nullable=True),
    sa.Column('thirdSection_RightConceptTwo_BlueHighlightText', sa.String(length=200), nullable=True),
    sa.Column('thirdSection_RightConceptTwo_Title', sa.String(length=200), nullable=True),
    sa.Column('thirdSection_RightConceptTwo_Description', sa.String(length=200), nullable=True),
    sa.Column('thirdSection_LeftConceptThree_BlueHighlightText', sa.String(length=200), nullable=True),
    sa.Column('thirdSection_LeftConceptThree_Title', sa.String(length=200), nullable=True),
    sa.Column('thirdSection_LefttConceptThree_Description', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('text_thirdsection')
    op.drop_table('text_secondsection')
    op.drop_table('text_fourthsection')
    op.drop_table('text_firstsection')
    op.drop_table('media')
    op.drop_table('user')
    # ### end Alembic commands ###
