"""empty message

Revision ID: 8d42f34d2086
Revises: 807d7c6c3216
Create Date: 2022-12-06 17:09:52.006525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d42f34d2086'
down_revision = '807d7c6c3216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_firstsection', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['mainTitle'])
        batch_op.create_unique_constraint(None, ['mainDescription'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_firstsection', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
